### ISSUE TITLE
Code Stealer

### ISSUE THREAD

**Issue by MistressPlague** [ERROR0418/EmmVRCPatcher#1]
You forgot to hide the DnSpy RVA/Tokens, code stealer. : )

**Comment by ERROR0418** [comment]
Its not stolen but k, look at the commit history, loosing files is a thing Krewella

**Comment by ERROR0418** [comment]
Also you actually know me 😉
![81d990bcd1f9df2d7c288f3ec3bb0d1c](https://user-images.githubusercontent.com/72815002/136671635-73e97701-dc52-4041-8fea-8da3e9473819.png)

**Comment by MistressPlague** [comment]
The only way those tokens are made is dnspy fam

Also, that's a banned acc; i don't know you personally

**Comment by MistressPlague** [comment]
Also, first file upload commit of actual code DNSpy tokens were present

**Comment by ERROR0418** [comment]
Yes, those are from DnSpy "fam", I lost the entire project when my drive failed, grabbed it back from someone I sent it to and used DnSpy to get the code back.

**Comment by MistressPlague** [comment]
uh huh, mhm

**Comment by MistressPlague** [comment]
I'll leave you to your project losing. 

/shrug af

**Comment by ERROR0418** [comment]
Also this is old af, probably doesn't work anymore, Originally privated it because emm told me to and gave me access to their private repos in exchange, they recently removed me, so I made it public again

**Comment by MistressPlague** [comment]
Sounds like a boring battle lol

**Comment by ERROR0418** [comment]
Really is ngl

**Comment by MistressPlague** [comment]
/shrug

discord is Mistress Plague#0 0 0 1 if you want to blabber, github is shite for this
(Spaced out as github plebby)
